matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
     - os: linux
      services: docker
 language: node_js
node_js:
  - "10.4.1"
 cache:
  directories:
    - node_modules
    - hummingbird-desktop/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
 before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
 before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install libusb-1.0-0-dev;
      sudo apt-get install libudev-dev;
    fi
  - npm i -g npm@6.1.0
 script:
  - npm install
  - npm run lint
  - cd hummingbird-desktop
  - npm install
  - npm run build
  - npm test
 branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"